Search
matiasm15/yisty-app pull request #4
Opened 2021-01-30 04:37 UTC by matiasm15

2021-02-05 22:37 UTC, evacalla requested changes

2021-02-05 22:37 UTC, evacalla commented on lib/models/profile.dart
> +    return product.id % 3 == 1;
¿Cuál es la funcionalidad de esto?

2021-02-05 22:37 UTC, evacalla commented on lib/models/profile.dart
> +    return product.id % 3 == 2;
Lo mismo acá

2021-02-05 22:37 UTC, evacalla commented on lib/screens/history/history_page.dart
> +              return const EmptyPage(
No hay manera de safar en flutter para no tener tanta salida "return"?

2021-02-05 22:37 UTC, evacalla commented on lib/screens/home/home_page.dart
> +            Subtitle(text: 'NOTICIAS')
Sería una buena practicar tener definido los String en un clase al estilo i18n y de ahí vamos referenciando lo que necesitamos, con esto evitamos tener duplicados.

2021-02-05 22:37 UTC, evacalla commented on lib/screens/search/product_search.dart
> +    }
```suggestion
    if (query == '') {
      return <Widget>[];
    } 
    return <Widget>[
      IconButton(icon: const Icon(Icons.close), onPressed: () {
        query = '';
       })
     ];
    }
```
Lo dejaría así, ya que de igual manera si no se cumple la condición sale por el otro lado, también lo hace más legible segun el amigo code clean

2021-02-05 22:37 UTC, evacalla commented on lib/services/base_service.dart
> +        }
```suggestion
         filtersString = '$filtersString&$key=$value';       
```
Idem de legible

2021-02-05 22:37 UTC, evacalla commented on lib/services/rest_client/rest_client.dart
> +    }
```suggestion
      authHeaders = <String, String>{'Authorization': 'Bearer $accessToken'};
```

2021-02-05 22:37 UTC, evacalla commented on lib/util/date_time_utils.dart
> +  }
Esto podria quedar más legible si definis al comienzo un String vacio & si cumple alguna condición se lo asignas así evitas tener varios puntos de retorno, también ese if else se puede mejorar

2021-02-05 22:37 UTC, evacalla commented on lib/widgets/products/product_preview.dart
> +    }
```suggestion
      return Row(
          children: <Widget>[
            const Icon(Icons.local_offer, size: 18, color: Colors.blueAccent),
            Text(' $shopsQuantity', style: const TextStyle(fontSize: 18, color: Colors.blueAccent, fontWeight: FontWeight.bold))
          ]
      );
```

2021-02-05 22:37 UTC, evacalla commented on lib/widgets/products/product_preview.dart
> +    }
No me gusta ese else if, es preferible que sea if

2021-02-07 20:38 UTC, matiasm15 commented on lib/models/profile.dart
> +    return product.id % 3 == 1;
Es para maquetar el funcionamiento, necesito que esta info venga del backend.

2021-02-07 20:38 UTC, matiasm15 commented on lib/models/profile.dart
> +    return product.id % 3 == 2;
Same.

2021-02-07 20:46 UTC, matiasm15 commented on lib/screens/search/product_search.dart
> +    }
No tengo porque desconfiar del amigo code clean.

2021-02-07 20:46 UTC, matiasm15 commented on lib/services/base_service.dart
> +        }
Mucho code clean, pero poca practica.

2021-02-07 20:48 UTC, matiasm15 commented on lib/widgets/products/product_preview.dart
> +    }
No quiero elevar el nivel de identado, puedo quitarles puntos de retornos como dice el Code Clean.

2021-02-07 20:52 UTC, matiasm15 commented on lib/services/rest_client/rest_client.dart
> +    }
Donde te sentaste amiguito.

2021-02-07 21:01 UTC, matiasm15 commented on lib/screens/history/history_page.dart
> +              return const EmptyPage(
Dart es como cualquier otro lenguaje que devuelven resultados solo si poner `return`, no tiene returns implicitos.

2021-02-07 21:13 UTC, matiasm15 commented on lib/util/date_time_utils.dart
> +  }
Pasame como mejorarias el else if. Quite los multiples puntos de retorno.

2021-02-08 23:09 UTC, evacalla approved these changes

2021-02-08 23:10 UTC, merged